name: Handle PR
on:
  push:
    branches: 
      - master
    
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: dotnet test --Configuration Release
