name: Unit Tests
on:
  push:
    branches: 
      - master
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
      - review_requested    
  
#   check_run:
#     types: [rerequested, requested_action]
    
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: dotnet test --configuration Release
