name: Update Dependencies
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dotnet Outdated
      run: dotnet tool install --global dotnet-outdated
    - name: Restore Packages
      run: dotnet restore
    - name: Update Packages
      run: dotnet outdated -u 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Update NuGet Dependencies
